# Generated by Django 4.2.1 on 2023-05-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('beauty_title', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('other_titles', models.CharField(blank=True, max_length=100, null=True)),
                ('connect', models.CharField(blank=True, max_length=100, null=True)),
                ('winter', models.CharField(blank=True, max_length=50, null=True, verbose_name='Зима')),
                ('summer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Лето')),
                ('autumn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Осень')),
                ('spring', models.CharField(blank=True, max_length=50, null=True, verbose_name='Весна')),
                ('status', models.SmallIntegerField(choices=[(1, 'New'), (2, 'Pending'), (3, 'Accepted'), (4, 'Rejected')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalCoords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SprActivitiesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserTourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=155)),
                ('last_name', models.CharField(blank=True, max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.BinaryField(null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('data_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='api.perevaladded')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.perevalareas')),
            ],
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='coords',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.perevalcoords'),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='pereval_areas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.perevalareas'),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='user_tourist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usertourist'),
        ),
    ]
